### ISSUE TITLE
Animations on drains

### ISSUE THREAD

**Issue by CourtneyCromley** [citizenlabsgr/adopt-a-drain#106]
Animation with the drains on the map – like when you scroll to a place on the map you haven’t been and they all “fall” from the top and how any drain you adopt just keeps bouncing forever.

**Comment by CourtneyCromley** [comment]
Adopted drains are hard for people to see.
Once “adopted” a drain it disappeared from the screen and people had to manually refresh the webpage to make it appear again.
After refreshing the adopted drains were being displayed as red and not grey.

**Comment by CourtneyCromley** [comment]
The drains do not appear on internet explorer.

**Comment by beyondtheteal** [comment]
@CourtneyCromley, can you clarify your initial comments? Do you want to remove the animation that falls from the top and just have them appear in place? 
Is the 4 bounces for the adopted drain acceptable?

**Comment by CourtneyCromley** [comment]
Yes I think 4 is acceptable. One of the comments we received from people checking out the site was that the drains never stopped bouncing and they would like them to eventually stop. I think 4 would be a fine amount of bounces.

**Comment by beyondtheteal** [comment]
The second comment is a little confusing, but I have some 'refresh' code done that might resolve the issue. I haven't pushed yet because tests need to be written.

**Comment by beyondtheteal** [comment]
## Behavior added by this issue
To begin, **My Drains** list is empty
<img width="928" alt="screen shot 2019-03-05 at 3 32 09 pm" src="https://user-images.githubusercontent.com/39837332/53842384-4dc12700-3f6d-11e9-8d79-35e565c49a9e.png">

When the **Adopt!** button is pressed, the drain name is automatically listed in **My Drains** with no refresh needed
<img width="928" alt="screen shot 2019-03-05 at 3 32 52 pm" src="https://user-images.githubusercontent.com/39837332/53842385-4dc12700-3f6d-11e9-8ea4-2ff1b48e3e2e.png">

When the **Abandon this drain** button is pressed (and then confirmed in the popup), the drain name is automatically removed from **My Drains** with no refresh needed
<img width="927" alt="screen shot 2019-03-05 at 3 33 08 pm" src="https://user-images.githubusercontent.com/39837332/53842386-4dc12700-3f6d-11e9-9ed5-4bfcb8130c70.png">
