### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by CourtneyCromley** [citizenlabsgr/adopt-a-drain#107]
The twitter handle is wrong but goes to the right page, the handle needs to be LGROW_GVMC 

The twitter hashtag that reads “#LGROWSewer” but leads you to “#sfsewer”

**Comment by beyondtheteal** [comment]
I'm assuming @LGROWWater is the wrong handle? 

File: /app/views/sidebar/_guidelines.html.haml 
Handle: line 74
Hashtag: line 78

It'd probably be best to move the Twitter handle to some sort of Global.

**Comment by CourtneyCromley** [comment]
Our twitter is @LGROW_GVMC Instagram is @lgrow_org and our facebook is LGROW.org

**Comment by beyondtheteal** [comment]
### **Before**
<img width="351" alt="screen shot 2019-02-24 at 4 51 56 pm" src="https://user-images.githubusercontent.com/39837332/53305881-9fbeca00-3854-11e9-9d8d-5b8539cd901d.png">

### **After**
<img width="335" alt="screen shot 2019-02-24 at 4 52 32 pm" src="https://user-images.githubusercontent.com/39837332/53305882-9fbeca00-3854-11e9-8f69-4910c981e9aa.png">

**Comment by cara-lgrow** [comment]
twitter handle links correctly, but the text in this pop up is incorrect. Refer to a different PR.
