### ISSUE TITLE
Update Readme (add reference to Citizen Labs)

### ISSUE THREAD

**Issue by Allen616** [citizenlabsgr/adopt-a-drain#11]
Add Citizen Labs elements to Readme

**Comment by Allen616** [comment]
Pull Request for this. Updated project contacts and screenshot (now showing Michigan instead of SF).

**Comment by CourtneyCromley** [comment]
Does this mean the LGROW logo right above the feedback icon?

**Comment by jacebrowning** [comment]
I think this can be closed now.
