### ISSUE TITLE
Password reset does not work

### ISSUE THREAD

**Issue by boekesteine** [citizenlabsgr/adopt-a-drain#112]
Tried the reset password option and got the following auto email:
Hello eileen.boekestein@gvmc.org!

Someone has requested a link to change your password. You can do this through the link below.

Change my password

If you didn't request this, please ignore this email.

Your password won't change until you access the link above and create a new one.

*******
The link to Change Password goes to http://adoptadrain-lgrow.org/?reqp=1&reqr=  

This is not a functional website, although we do own the domain

**Comment by cara-lgrow** [comment]
I just tried the password reset, and it worked!!!! However, can we change the 'no-reply' email address that sends the email. LGROWWATER.org is not a domain that we own, and therefore I previously thought this was  phishing attempt.

**Comment by jacebrowning** [comment]
That's great to hear!

We've got the email change documented on https://github.com/citizenlabsgr/adopt-a-drain/issues/143 so I think we can close this one.
