### ISSUE TITLE
Default Drain Name

### ISSUE THREAD

**Issue by cara-lgrow** [citizenlabsgr/adopt-a-drain#113]
Adopted drains that are NOT named by the adopter are currently called 'Storm Water inlet drain' please change to 'Storm Drain' for the program to remain consistent.

Also, for future reference, stormwater is 1 word.

# Solution 
* Short term,  change the 'Storm Water inlet drain' to 'Storm Drain' in the code -JW

# Strategy
* Long term, start planning on creating admin app to make this sort of change easy for LGROW to do on the fly.

**Comment by beyondtheteal** [comment]
I'll commit the code and tested with manual changes in the postgres DB, but it won't appear for everyone until the data.world data is updated.

**Comment by Wilfongjt** [comment]
## The data curator (LGROW) needs to provide a new CSV file to change the default "drain name."

### Goal
* Allow the curator to control the default "drain name"

### To refresh everyone's memory ;), 
* The original data is provided by LGROW in the form of a CSV file.
* The data is processed by a script (Jupyter-notebook data wrangling section) by a developer. 
* As a temporary measure, the column dr_type is forcibly added and set to 'Storm Water inlet drain.'
* dr_type is then used as the default "drain name" when an adoption occurs.
* The processed data is uploaded to data.world and shared with Adopt-a-drain.
* The complete process is found at https://github.com/citizenlabsgr/data.world 

### Solution
The curators of the data (LGROW) needs to add a column to CSV provided to refresh the .
* name the column 'drain_type'
* set 'drain_type' to 'Storm Drain'
* follow the "Quick Start" process found at https://github.com/citizenlabsgr/data.world 
* a developer needs fix the hardcoded "dr_type" in the Jupyter-Notebook (scripts/adopt-a-drain/01.Dev.Process.ipynb)

**Comment by beyondtheteal** [comment]
@Wilfongjt Is there a reason we need to include the default value in the database? I know the pins populate based on if they matched (your code comment), but is that needed?

**Comment by Wilfongjt** [comment]
There are many ways to accomplish this change. I usually do this when I expect the label to change and I've already changed it once.  Essentially, I've moved changing these labels from a development process to an operations process.  Developers can really get bogged down editing text in the code.  This is the tip of the iceberg.

# The Goal
* Make the application Customizable by non-developers.
# Strategy
* Move all default values to the database
* Move all configurable text to the database (FAQ, Terms of Use,...)
* Build an application to manage the defaults and configurable text
* Convert all text to something like markdown language. 
  
# That said:
* I believe you have convinced me that it will be faster to just make the change in the code for now and check of a Priority-1 issue.
* We won't change in the code again.

**Comment by Wilfongjt** [comment]
# QA Review Instructions
* Confirm that “Storm Drain” appears as default when adopting a drain

## Prerequisites 
* None

## How to check:
* https://lgrow-staging.herokuapp.com
* LOGIN with a valid email address and password
* FIND the MAP
* ADOPT by clicking on a drain symbol
* FIND Label “Give this drain a name ”
* FIND Textbox containing “Storm Drain”

# Notify Others
* WAFFLE: https://waffle.io/citizenlabsgr/adopt-a-drain
* MOVE issue to QA-Failed or QA-Passed

**Comment by cara-lgrow** [comment]
This issue might be resolved when we re-upload the new data that LGROW will provide

**Comment by cara-lgrow** [comment]
This looks good in the app now!

**Comment by Wilfongjt** [comment]
# Resolved
Moved to QA-Passed
