### ISSUE TITLE
Phone Number

### ISSUE THREAD

**Issue by CourtneyCromley** [citizenlabsgr/adopt-a-drain#115]
When you sign in for the first time and try to edit your information, the system requires that you enter a cell phone number or leave the preset one in place.
Please remove this requirement

**Comment by beyondtheteal** [comment]
I am not able to reproduce this on the master branch. 
The grey text is a suggestion but it's not stored in the database. We should at least update the suggested address to be near Grand Rapids.

<img width="351" alt="screen shot 2019-02-24 at 4 35 46 pm" src="https://user-images.githubusercontent.com/39837332/53305668-45bd0500-3852-11e9-9f94-964ff3065f7c.png">

**Comment by Wilfongjt** [comment]
don[t want extra data to protect so no.
