### ISSUE TITLE
Displaying options

### ISSUE THREAD

**Issue by CourtneyCromley** [citizenlabsgr/adopt-a-drain#116]
Having the ability to toggle on & off google aerials would be helpful. Being able to see the aerial locations of catch basins by using local 
landmarks has been a topic from many of the people trying out the website.

**Comment by beyondtheteal** [comment]
Just to confirm, do you mean allowing the user to switch to **Satellite View**?

If yes, all we need to do is change `mapTypeControl` to `true` in `main.js.erb line 16`.

**Comment by CourtneyCromley** [comment]
Yes we have been given lots of feedback asking for Satellite View.
