### ISSUE TITLE
Second Adoption Email (Content)

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#118]
# Edit and Review Content
## Original Content
https://docs.google.com/document/d/1hSdcP2R-BYs_rOsgi9LeOsgucnTjU7nfVXTcBVUmki4/edit?usp=sharing

**Comment by cara-lgrow** [comment]
LGROW edited. Ready to go at: https://docs.google.com/document/d/1hSdcP2R-BYs_rOsgi9LeOsgucnTjU7nfVXTcBVUmki4/edit
In 'Adopt a Drain' google drive folder doc title: 'Email: Second Adoption'

@Wilfongjt @beyondtheteal
