### ISSUE TITLE
Second Adoption Email (Code)

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#119]
# Update email/page with new content

### Content Source
https://docs.google.com/document/d/1hSdcP2R-BYs_rOsgi9LeOsgucnTjU7nfVXTcBVUmki4/edit?usp=sharing 

### Target File
/app/views/thing_mailer/second_adoption_confirmation.html.erb

**Comment by Wilfongjt** [comment]
# Review Instructions
## Adopt a second drain using the map
How to check:
* https://lgrow-staging.herokuapp.com
* LOGIN with a valid email address and password
* FIND the MAP
* ABANDON any previously adopted DRAINS
* ADOPT first DRAIN
* ADOPT second DRAIN
* WAIT for emails to show up
* OPEN email with 'Thanks for adopting another drain'' subject line
* COMPARE: EMAIL to DOCUMENT at  https://docs.google.com/document/d/1hSdcP2R-BYs_rOsgi9LeOsgucnTjU7nfVXTcBVUmki4/edit?usp=sharing

**Comment by Wilfongjt** [comment]
LGROW edited. 
CHANGES Ready to go at: https://docs.google.com/document/d/1hSdcP2R-BYs_rOsgi9LeOsgucnTjU7nfVXTcBVUmki4/edit
In 'Adopt a Drain' google drive folder doc title: 'Email: Second Adoption'

**Comment by beyondtheteal** [comment]
I noticed that this email has a different city points code. Making the changes but including them in the PR for the changes for the first email.

**Comment by Wilfongjt** [comment]
no longer an an issue
