### ISSUE TITLE
Third Adoption Email (Content)

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#120]
# Edit and Review Content
## Original Content
Google doc https://docs.google.com/document/d/1gineOuncxf3OI6RMZs1AOXRfEx0M6UvVfpw6UisPMNU/edit?usp=sharing

**Comment by cara-lgrow** [comment]
content updated. can be found here: https://docs.google.com/document/d/1gineOuncxf3OI6RMZs1AOXRfEx0M6UvVfpw6UisPMNU/edit

in the google drive folder 'Adopt a Drain' doc titled: Email: Third Adoption Email

@Wilfongjt @beyondtheteal

**Comment by cara-lgrow** [comment]
refer to issue # 121
