### ISSUE TITLE
Update staging environment params

### ISSUE THREAD

**Issue by beyondtheteal** [citizenlabsgr/adopt-a-drain#126]
In `config/environments/staging.rb`, there is still a reference to `adoptadrainsf-staging`. Update this link. 

Also consider doing a code search for `sf`, as there are several references that still need to be updated. 
Examples: 
* app/models/thing.rb
* app/views/sidebar/_guidelines.html.haml
* app/views/thing_mailer/first_adoption_confirmation.html.erb
* app/views/thing_mailer/second_adoption_confirmation.html.erb
* config/locales/en.yml
* test/models/thing_test.rb

**Comment by Wilfongjt** [comment]
Sf is issue #28.

**Comment by Wilfongjt** [comment]
Can you exlain the staging.rb change for this non-ruby guy.

**Comment by beyondtheteal** [comment]
I don't understand it fully myself yet. If it's unneeded, perhaps we should remove the file that has the SF link then.

**Comment by Wilfongjt** [comment]
# staging.rb
config.action_controller.asset_host = "https://#{ENV['HEROKU_APP_NAME'] || 'adoptadrainsf-staging'}.herokuapp.com/"
  
* The code switches from using the env variable to the hard coded value.  
* HEROKU_APP_NAME is NOT defined in grow-staging therefore is NOT used in staging.rb.
* https://adoptadrainsf-staging.herokuapp.com/ points to SF's staging app by default
* config.action_controller.asset_host is used to set config.action_mailer.asset_host     
* config.action_mailer.asset_host is never used or reset... dead end.

## I believe this was an abandoned attempt to switch the url to the SMTP host

This is a common pattern in AAD :)

**Comment by Wilfongjt** [comment]
All done.
