### ISSUE TITLE
Docker does not persist database changes locally

### ISSUE THREAD

**Issue by beyondtheteal** [citizenlabsgr/adopt-a-drain#129]
When I `ctrl+c` to stop Docker, it claims that it is gracefully closing the database. 

``` ^CGracefully stopping... (press Ctrl+C again to force)
Stopping adopt-a-drain_web_1 ... done
Stopping adopt-a-drain_db_1  ... done
```

However, when I `docker-compose up` again, I get 
``` 
db_1   | LOG:  incomplete startup packet
......
db_1   | ERROR:  database "adopt_a_thing_development" already exists
db_1   | STATEMENT:  CREATE DATABASE "adopt_a_thing_development" ENCODING = 'utf8'
```
And my data doesn't exist.

**Comment by Wilfongjt** [comment]
OK. This is as designed. Use docker-compose down. Avoid use ctrl-c to shut down Docker. If you have to use ctrl-c the you will have ro find and delete the "server.pid" file somewhere in the apps /tmp folder.

**Comment by beyondtheteal** [comment]
Thanks! I had to run the command in a separate window, but it worked!

**Comment by beyondtheteal** [comment]
This is still not working for me. Perhaps we can troubleshoot together next CL meeting.

**Comment by beyondtheteal** [comment]
I added more memory to Docker, as suggested in the link below, and it seemed to clear up the issue 
https://www.petefreitag.com/item/848.cfm
