### ISSUE TITLE
My Drain on Mobile Website

### ISSUE THREAD

**Issue by CourtneyCromley** [citizenlabsgr/adopt-a-drain#132]
When using the mobile website the drains you have adopted are not showing up in the "My Drains" section of the web page. I had to leave the mobile website and re-log in before I could see the drains I have adopted. Can we have the drains that have been adopted pop up in the "my drains" location on the home page of the mobile website?

**Comment by Wilfongjt** [comment]
# Do you have a refresh button on your mobile browser?
Help me out here, are you saying that you adopt a drain on your mobile device but it doesn't automatically show in your list of adopted drains.

Refresh my memory, does the non-mobile site refresh the "My Drains" list automatically?

**Comment by beyondtheteal** [comment]
"My Drains" do not refresh automatically, but I think they should. I imagine that's what she's experiencing here because the refresh button is hard to find on some phones.

**Comment by beyondtheteal** [comment]
Code is done, but not pushed yet because tests need to be written.

**Comment by beyondtheteal** [comment]
## Behavior added by my pull request 

1. Click on a map marker that is not adopted. The map marker info window should say **"Sign in to adopt this drain"**
<img width="770" alt="screen shot 2019-03-05 at 3 38 05 pm" src="https://user-images.githubusercontent.com/39837332/53842679-333b7d80-3f6e-11e9-8d40-1fd546c61f5c.png">

2. Sign in. The map marker info window should change to say **"Adopt this drain"**
<img width="763" alt="screen shot 2019-03-05 at 3 37 54 pm" src="https://user-images.githubusercontent.com/39837332/53842676-32a2e700-3f6e-11e9-8841-666530c257f6.png">

3. Adopt the drain. The map marker info window should change to say **"Thank you"**
<img width="646" alt="screen shot 2019-03-05 at 3 42 46 pm" src="https://user-images.githubusercontent.com/39837332/53842681-333b7d80-3f6e-11e9-939e-38672ed05b15.png">

4. Sign out. The map marker info window should change to say **"This drain is adopted by..."**
<img width="645" alt="screen shot 2019-03-05 at 3 42 29 pm" src="https://user-images.githubusercontent.com/39837332/53842680-333b7d80-3f6e-11e9-8771-d08e336d7647.png">

**Comment by beyondtheteal** [comment]
@cara-lgrow or @CourtneyCromley, please review this on Staging to ensure that it handles the concerns in the original ticket. Thanks!

**Comment by cara-lgrow** [comment]
looks good and works on my android.
