### ISSUE TITLE
Kent County Drain Locations

### ISSUE THREAD

**Issue by boekesteine** [citizenlabsgr/adopt-a-drain#14]
Add catch basin locations to map for Kent County communities . We are still collecting Ottawa Co. data - it is not stored in REGIS so we need to get each community's info separately. This should be a good starting point though. Excel and CSV versions uploaded to Slack (file types not allowed in Waffle). In this file, use Drain_Owner as the city ID. I am not sure what drain type and system use code would correspond to in ours since those seem to identify combined vs separated sewers and all ours are separated.

**Comment by Wilfongjt** [comment]
This is an operations task.  We have data loading process worked out in the [data.world repo](https://github.com/citizenlabsgr/data.world)

**Comment by cara-lgrow** [comment]
@Wilfongjt is there a way for me to see the excel file of data that we provided you with previously? The one that the current app is pulling drain locations from? I want to be able to provide you with the same columns (plus a unique user ID like we talked about), but with the data we actually want displayed on the app.

**Comment by Wilfongjt** [comment]
@cara-lgrow CSV will not attach here so check your email

**Comment by Wilfongjt** [comment]
done for April launch. no longer an issue
