### ISSUE TITLE
Install LetterOpener gem for local dev

### ISSUE THREAD

**Issue by BrandonKlotz** [citizenlabsgr/adopt-a-drain#140]
LetterOpener is a gem for `Previewing mail in the browser instead of sending.` I have found this speed up my development process when working on Rails apps that send user emails/notifications. This can be helpful for quickly viewing the design of an email in the browser.

https://github.com/ryanb/letter_opener

**Comment by beyondtheteal** [comment]
Hey Brandon, with the changes I made for #75, we can preview emails in the browser. Does that satisfy the need for this gem?

**Comment by BrandonKlotz** [comment]
My thought was it would be a nice enhancement if other cities fork this repo and if more dev is done for email notifications. I think this is still a desired story but maybe not the highest priority.

**Comment by Wilfongjt** [comment]
What is Letter Opener and why is it important?

**Comment by BrandonKlotz** [comment]
@Wilfongjt Updated the issue description 😓 should be there in the first place 😄
