### ISSUE TITLE
DeviseMailer secret_key in repo

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#144]
I see that the DeviseMailer secret_key is available and in plain sight in the repo. I know next to nothing about Ruby security and settings but when something named secret_key is stored in the repo, in plain sight to the world, I automatically think bad, bad, very bad! 

If you have knowledge of the devise secret_key please offer counsel:
* where does the devise secret_key come from?
* Should we move this to a heroku environment variable?

**Comment by Ross-Hunter** [comment]
1) If not set it defaults to the secret keys of rails itself, I'm not sure why this was set explicitly.
2) Yes

PR ready.
