### ISSUE TITLE
Enable SSL on grow-staging

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#145]
# Configure lgrow-staging SSL
The grow-staging url is https://lgrow-staging.herokuapp.com but the lgrow-staging settings say "You will need to enable SSL on your app"

Would someone with more heroku experience please take a go at configuring the heroku lgrow-staging SSL in the "Domains and certificates" section of lgrow-staging.

**Comment by jacebrowning** [comment]
It should be working now: https://lgrow-staging.herokuapp.com/

**Comment by beyondtheteal** [comment]
Seems to work. Thanks, Jace!
