### ISSUE TITLE
Enable Outgoing Email for LGROW

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#159]
# Enable out going Email for LGROW
AAD is currently using SF's SMTP server and good neighbors shouldn't abuse the courtesy 
## Problems
* Does sending email  require Heroku instance configuration or if this is a ruby thing?
* Dependency on a service outside our control makes AAD vulnerable to failure.
## Solutions
* figure out how to configure our Heroku instance to send email
* or figure out the MailChimp API and integrate into AAD
* Update readme.md to give instructions on how to setup outgoing email.

**Comment by jacebrowning** [comment]
> AAD is currently using SF's SMTP server

Where do you see this?

As far as I can tell we are using SendGrid (provisioned by Heroku) to send emails on staging.
