### ISSUE TITLE
Tag 'Basin Buddy' somewhere on the app

### ISSUE THREAD

**Issue by cara-lgrow** [citizenlabsgr/adopt-a-drain#172]
Looking through LGROW.org's search history, we are getting many searches for 'Basin Buddy.' In order to direct people to the site who may be searching for it under 'Basin Buddy,' would it be possible to tag those words on the app in order to direct them to the correct place?

**Comment by Wilfongjt** [comment]
I'm not real sure that I'm clear. Let me try to explain what I'm understanding.

The LGROW.org search feature returns a more or less empty search result.  LGROW would like this page to return a link to Basin Buddy?

**Comment by jacebrowning** [comment]
I think @cara-lgrow is referring to SEO here. They want to increase the chance that someone searching Google for "basin buddy" will end up on the new site.

**Comment by cara-lgrow** [comment]
@jacebrowning yes! LGROW can tag 'basin buddy' on the LGROW site (I'll take care of that part) and redirect people to the new site, but I was wondering if there was something that you guys could do on the new site that would direct people googling 'basin buddy' to the Adopt a Drain site.

**Comment by cara-lgrow** [comment]
@jacebrowning yes! LGROW can tag 'basin buddy' on the LGROW site (I'll take care of that part) and redirect people to the new site, but I was wondering if there was something that you guys could do on the new site that would direct people googling 'basin buddy' to the Adopt a Drain site.

**Comment by beyondtheteal** [comment]
This page may be helpful for implementation: https://medium.com/la-revanche-des-sites/seo-ruby-on-rails-the-comprehensive-guide-2018-b4101cc51b78

**Comment by Wilfongjt** [comment]
city took care of this no longer an issue
