### ISSUE TITLE
Add "date adopted" column to drains table

### ISSUE THREAD

**Issue by beyondtheteal** [citizenlabsgr/adopt-a-drain#176]
## Request
Add "date adopted" column to drains table

## Purpose 
* This column would be displayed to the user in the `info_window`
* as well as be used to send reminder emails on the anniversary date of adoption
* also a part of retention strategy

See comment: https://github.com/citizenlabsgr/adopt-a-drain/issues/150#issuecomment-470197582

**Comment by Wilfongjt** [comment]
The column needs a default ... 
    CREATE TABLE my_table
    (
    id serial PRIMARY KEY not null,
    my_date date not null default CURRENT_DATE
    );

**Comment by beyondtheteal** [comment]
@Wilfongjt Did you already create this column? I don't see it in my database.

**Comment by Wilfongjt** [comment]
Updating tests.

**Comment by Wilfongjt** [comment]
# Solved
 date_adopted added then changed to adopted_at to conform to current naming style.
