### ISSUE TITLE
Check markers for contrast for people who are color blind

### ISSUE THREAD

**Issue by beyondtheteal** [citizenlabsgr/adopt-a-drain#177]
I found a website that you can plug a URL into and get a synthesized color-blind view. Determine if the contrast between "Adopted Drains" and "My Drains" is different enough. 

https://www.toptal.com/designers/colorfilter?orig_uri=https://lgrow-staging.herokuapp.com&process_type=protan

<img width="570" alt="Screen Shot 2019-03-10 at 11 26 40 PM" src="https://user-images.githubusercontent.com/39837332/54098727-1c40c500-438c-11e9-90ea-59d3e176ac2e.png">

**Comment by Wilfongjt** [comment]
I like this map better than the actual map.  Blue tends to hold up best.  The red was always a bad ADA choice.  

I would suggest changing the "Adopted by you" color to black.    This would help both color sighted and color blind folks.  Also it would enhance the "Adopted by you" symbol's figure-ground making "Adopted by you" symbols easier to spot.

**Comment by cara-lgrow** [comment]
Our resident color blind GVSU grad student ok'd the current map. They symbols are different enough for him to see. We can keep the map as-is.

**Comment by beyondtheteal** [comment]
Closing issue based on Cara's comment!
