### ISSUE TITLE
Mascot Image in 1st and 2nd adopt email 

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#184]
# Issue
drain-cleaner.png is a copy of the adopt-a-drain.png.  
# Solution
* replace drain-cleaner.png with the attached drain-cleaner.png
<img width="214" alt="drain-cleaner" src="https://user-images.githubusercontent.com/3185699/54431258-51d30e80-46fc-11e9-8e48-d6dae50b0391.png">

**Comment by Wilfongjt** [comment]
# QA
## Adopt a second drain using the map
How to check:
* GOTO https://lgrow-staging.herokuapp.com
* LOGIN with a valid email address and password
* FIND the MAP
* ABANDON any previously adopted DRAINS
* ADOPT first DRAIN
* ADOPT second DRAIN
* WAIT for emails to show up
* OPEN email with "Wow! Thank you for adopting another drain." subject line
* COMPARE: EMAIL to DOCUMENT at  https://docs.google.com/document/d/1hSdcP2R-BYs_rOsgi9LeOsgucnTjU7nfVXTcBVUmki4/edit?usp=sharing

**Comment by Wilfongjt** [comment]
Both 1st and 2nd email Images show slowly but they do appear.

**Comment by cara-lgrow** [comment]
seems to come through on the users end.

**Comment by Wilfongjt** [comment]
# Is this resolved?

**Comment by cara-lgrow** [comment]
it comes though perfect now. However, I think I'm going to change the pic. I want one of our interns to add text over the image to say Thank you (and identify Major Runoff). I will update with updated email language.
ETA Monday 4.1.19

**Comment by cara-lgrow** [comment]
I like the first option for the first email, and use the second photo for the second email.  And whichever one you choose for the third email. What do you think @beyondtheteal  ?

**Comment by beyondtheteal** [comment]
Looks great!
