### ISSUE TITLE
Welcome email needs to change

### ISSUE THREAD

**Issue by cara-lgrow** [citizenlabsgr/adopt-a-drain#194]

**Comment by cara-lgrow** [comment]
The 1st welcome email is not current. Missing text: For residents of Kent County who are eligible for GR City Points, use the code L8H2-RKF4 to redeem points in your GR City Points account at http://www.mygrcitypoints.com/

right above the major runoff photo

in google doc:
https://docs.google.com/document/d/1en7smcuMtIj7P-VY-JJT3_vkA2e7QFHzRLFAsLCnLeA/edit

**Comment by beyondtheteal** [comment]
@Wilfongjt, request to close this because it is current. The code is in the email footer and should show up on all "thank you" emails.

**Comment by Wilfongjt** [comment]
Cara says this is no longer an issues
