### ISSUE TITLE
Adopt a Drain Logo is too big in Outlook

### ISSUE THREAD

**Issue by cara-lgrow** [citizenlabsgr/adopt-a-drain#197]
The logo in the automated email shows up way too large, but only in Outlook. Photo now shows up fine. Reference email that Joel sent.

**Comment by cara-lgrow** [comment]
update- logo showed up ok in Outlook 365- so maybe this is only an issue in older versions of the program?

**Comment by beyondtheteal** [comment]
Below is what a 300px logo looks like on Web and Mobile. 

<img width="1045" alt="Desktop 300px" src="https://user-images.githubusercontent.com/39837332/55409066-4cb0f480-552f-11e9-91b4-0879b9b1ac38.png">
<img width="300" alt="Mobile 300px" src="https://user-images.githubusercontent.com/39837332/55409154-7702b200-552f-11e9-8f63-dd81583820d5.png">
