### ISSUE TITLE
Add video to app

### ISSUE THREAD

**Issue by cara-lgrow** [citizenlabsgr/adopt-a-drain#204]
add the Major Runoff 'training' video to the left sidebar in the app. 
Let Cara know what format you need the video sent in.

**Comment by beyondtheteal** [comment]
@cara-lgrow, I think the best way would be to host it on a video-serving site like YouTube and then embedding the link into our website. Let us know once you have the link for that and the code shouldn't take too long.

**Comment by cara-lgrow** [comment]
Check this out:
https://youtu.be/AVYB_flpp-g

It shows up pretty fuzzy to me. It uploaded better on our Facebook page!!!  Should we find a way other than YouTube to upload it?

**Comment by beyondtheteal** [comment]
It looks fine on my screen? Click the settings icon while the video is playing and make sure your computer is playing at 480p. 

Thanks!

**Comment by cara-lgrow** [comment]
user error- looks great at 480 p:)

**Comment by beyondtheteal** [comment]
Yay, I got it! I'll be submitting a PR shortly.

Key notes: 
1) The URL has to swap `/watch?v=` for `/embed/`
2) The video was filmed vertically, so there are some not-great black bars showing on the current version (see image) 
https://i.imgur.com/tjGhOgM.jpg
