### ISSUE TITLE
Decision about Sponsor Iogos (keep, remove, replace) 

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#21]
Make decision to keep, remove, replace sponsor logos (Water Power Sewer SF, SF Public Works, DataSF, code for SF, Code for America, SF Dept of Tech )

**Comment by cara-lgrow** [comment]
Logos showing should be Citizen Labs, and LGROW. If it is a Code for America code, do we need to keep them in there? We had not yet decided if we wanted each community logo listed...right now it is a short list, but could eventually get pretty extensive.

**Comment by Allen616** [comment]
I would remove Code for America logo as we are not a brigade of CfA.

**Comment by Wilfongjt** [comment]
I will remove Code for America.

**Comment by Wilfongjt** [comment]
done
