### ISSUE TITLE
What does it mean to adopt a drain pop up

### ISSUE THREAD

**Issue by cara-lgrow** [citizenlabsgr/adopt-a-drain#210]
This pop up needs to be updated with the most current information.
Can be found here: 
https://docs.google.com/document/d/1jDR7CmPc3Mi8NA7SUzjJTIkeebwmx8cQoTIJq857_OU/edit

Please keep the current linked social media icons in this pop up.

**Comment by Wilfongjt** [comment]
# Resolved
