### ISSUE TITLE
set default name to Storm Drain Failed-QA

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#212]
# Problem
The default value for the "Drain Name" should be "Storm Drain"

# Issue
QA Failed (reported by @cara-lgrow) .

**Comment by Wilfongjt** [comment]
# Question
What failed?
I see the default "Storm Drain" so is it failing for a different reason?

<img width="221" alt="Screen Shot 2019-03-27 at 09 08 58" src="https://user-images.githubusercontent.com/3185699/55078230-0b709e80-5070-11e9-926a-c86ef6ca4639.png">

<img width="290" alt="Screen Shot 2019-03-27 at 09 13 51" src="https://user-images.githubusercontent.com/3185699/55078528-be40fc80-5070-11e9-83b1-939229516303.png">

**Comment by cara-lgrow** [comment]
? I don't know. Looks good to me now....

**Comment by Wilfongjt** [comment]
# Resolved

**Comment by Wilfongjt** [comment]
# Resolved
