### ISSUE TITLE
Remove or Replace Adopt a Drain 30 Sec video

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#22]
The video is SF-centric, works but should be more GR Basin centric.

**Comment by cara-lgrow** [comment]
We will replace this with our own video (but we have not created one yet).

**Comment by Allen616** [comment]
Is the plan to create this in-house? I could reach out to some local people that create/produce video.

**Comment by boekesteine** [comment]
@Allen616 we are hoping to create it in-house. We have some folks who work with us that do video production. We are planning to do this over the next couple of months.

**Comment by cara-lgrow** [comment]
this will be replaced with @BrandonKlotz 's creation (and LGROW's help!)

**Comment by cara-lgrow** [comment]
I accidentally closed this issue. In the meantime, refer to Issue #204.
