### ISSUE TITLE
TERMS OF USE

### ISSUE THREAD

**Issue by cara-lgrow** [citizenlabsgr/adopt-a-drain#227]
The terms of use is NOT updated and consistent with what I have posted on the google drive. Please fix ASAP. This worries me as the sight is live, and the legal terms are not correct.

**Comment by beyondtheteal** [comment]
#229

**Comment by cara-lgrow** [comment]
this is now updated in the staging app. needs to be pushed to production

**Comment by Wilfongjt** [comment]
duplicate of 229
