### ISSUE TITLE
Remove user's names from drain info window

### ISSUE THREAD

**Issue by beyondtheteal** [citizenlabsgr/adopt-a-drain#230]
### Problem
We realized tonight that showing the name of the person who adopted a drain might be a security risk because generally the person lives within a couple of houses. 

### Resolution
Remove the "By: FirstName LastName" line from both info windows - the "adopted thank you" window and the "adopted" window.

**Comment by Wilfongjt** [comment]
This may have been a drive-by requirement that never made it to an issue.  This is definitely an LGROW decision. I would like the name to be kept as part of the account data. I believe we can use it to help out with deterring profanity in the drain names.

**Comment by beyondtheteal** [comment]
@Wilfongjt This issue might be resolved by #253

**Comment by Wilfongjt** [comment]
same as #255
