### ISSUE TITLE
1st adopt a drain email

### ISSUE THREAD

**Issue by cara-lgrow** [citizenlabsgr/adopt-a-drain#236]
the email says, 'thank you for adopting one of the Lower Grand River's 40,000+ stormdrains...' I thought I had deleted the 40,000 in the email so that we would not have to update the number as we get more communities participating?

**Comment by beyondtheteal** [comment]
@cara-lgrow Could you provide the link to the current welcome email so we can check? I'm having trouble finding it in our other issues.

**Comment by cara-lgrow** [comment]
https://docs.google.com/document/d/1en7smcuMtIj7P-VY-JJT3_vkA2e7QFHzRLFAsLCnLeA/edit
