### ISSUE TITLE
Drain Symbolism and Logic

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#24]
Do these symbols make sense for the GRB?
  
Should we keep, remove or replace:

- "Drains to Sewer"
- "Drains to Ocean/Bay"
- "Adopted"
- "Adopted by you"

**Comment by cara-lgrow** [comment]
[Things to include in the pop up.docx](https://github.com/citizenlabsgr/adopt-a-drain/files/2352786/Things.to.include.in.the.pop.up.docx)

We had shared this doc before you were on the project, James. Let me know if this helps...

**Comment by Wilfongjt** [comment]
Keep Drains
--------------------
Available
Adopted
Adopted by you

**Comment by Wilfongjt** [comment]
| map symbol | label | login | adopted |
|-- | -- | -- | -- | 
| grey heart  | Adopted | F  | T  | 
| green grill  | Available | F  | F  |
| orange heart | Adopted by you | T  | T  |

**Comment by Wilfongjt** [comment]
* Change "Available" symbol from green-grill to blue-waves

| map symbol | label | login | adopted |
|-- | -- | -- | -- | 
| grey heart  | Adopted | F  | T  | 
| blue-waves  | Available | F  | F  |
| orange heart | Adopted by you | T  | T  |

**Comment by Wilfongjt** [comment]
this is dependent on completion of #84 replacing the green-drain image with a blue-waves image.
