### ISSUE TITLE
Replace email info@sfwater.org with something 

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#29]
email in en.yml, where should this email go? what should the email be?

**Comment by jacebrowning** [comment]
I think we could use contact@citizienlabs.org. What do you think, @Allen616?

**Comment by Wilfongjt** [comment]
I've replace info@sfwater.org with hello@citizenlabs.org

**Comment by Wilfongjt** [comment]
replaced info@sfwater.org with hello@citizenlabs.org
