### ISSUE TITLE
Use Heroku release phase for migrations

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/adopt-a-drain#3]
The [instructions](https://github.com/citizenlabsgr/adopt-a-drain#deploying-to-heroku), don't mention it, but this is the proper way to do things.

The instructions also tell us to vender the precompiled assets, but we don't want to do that either.

**Comment by Wilfongjt** [comment]
This issue needs clarification.  How about a statement of the objective followed by a strategy to achieve the objective.
## Sample:

Objective:
* Give the illusion of a fast UI by avoiding the download all drains at one time.
* Have drains appear as user pans around screen

Strategy: 
* Define a rectangle representing the screen and limit drain query and download to drains within the rectangle.

**Comment by jacebrowning** [comment]
I believe that migrations are already running automatically.
