### ISSUE TITLE
Adopt-a-Drain SF (AAD-SF) uses an email address ( info@sfwater.org). Replace or remove? 

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#34]
Change 
* info@sfwater.org
To
* hello@citizenlabs.org

**Comment by Wilfongjt** [comment]
Steps:
* Updated: info@sfwater.org to hello@citizenlabs.org
* Tests: OK
* In heroic staging:

**Comment by boekesteine** [comment]
Is this a tech support email or a general program information email? If it's for people's questions about the adopt a drain program, it should come to LGROW. We are getting our tech guys to set up an email for the program - hoping it will be adoptadrain@lgrow.org
