### ISSUE TITLE
Terms of Use Agreement

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#35]
Rewrite or replace the Terms of Use?

**Comment by cara-lgrow** [comment]
Yes, we will have to replace this with our own.

**Comment by Wilfongjt** [comment]
Next step should be to transfer text from source code to google drive and share with LGROW writer.

**Comment by boekesteine** [comment]
Our plan is to replace SF references with GVMC/LGROW in the existing Terms of Use and then run it past our lawyers. Concern from municipalities is whether it covers them or just GVMC as far as liability is concerned.

**Comment by Wilfongjt** [comment]
# Review Instructions
## Compare app with Terms of Use google doc
How to check:
* https://lgrow-staging.herokuapp.com
* FIND:  "_By signing up, you agree to the Terms of Use_."
* CLICK ON:  Terms of Use
* COMPARE: Popup window with contents of google doc  https://docs.google.com/document/d/1GN-tCpH5zLh5rWs6_y_B-IkXu9h8AxhDsTPQVDmpgcY/edit?usp=sharing

**Comment by boekesteine** [comment]
We have edited the list of communities listed as Sponsoring Jurisdictions in the first paragraph of the Terms. Change was noted in the Google Doc. Please update in the app when possible.

**Comment by Wilfongjt** [comment]
New version i available 3/5/19

**Comment by cara-lgrow** [comment]
Refer to duplicate Issue #171
