### ISSUE TITLE
AAD-SF has disclaimer for City and County (_guidelines.html.haml). 

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#36]
To whom does our disclaimer apply?

**Comment by Wilfongjt** [comment]
Next step: setup disclaimer document in google drive to share with LGROW legal writer.

**Comment by Wilfongjt** [comment]
https://docs.google.com/document/d/1BHQe3nJ7LnlZWPV4YbgemG26WRAuRjOmp3_b0ug_qqI/edit?usp=sharing

**Comment by boekesteine** [comment]
Can we use this doc instead: https://docs.google.com/document/d/1-J2x_MrPedhn8VUEedcnr7xu8c6-wBiSeTHGyauDbBg/edit?usp=sharing

**Comment by cara-lgrow** [comment]
Refer to duplicate Issue #171
