### ISSUE TITLE
AAD-SF uses a youtube account (https://www.youtube.com/user/SFPUCcommunications). Replace or remove?  

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#42]

**Comment by cara-lgrow** [comment]
we do not currently have a you tube site. If we remove this now, could we add it back in if we needed it to show all of the training videos some day?

**Comment by Wilfongjt** [comment]
Yes, we can remove now and replace later. 

_guideline.html.haml
%a{target: "_blank", href: "https://www.facebook.com/SFWater", class: ""}
            =image_tag("icons/facebook.png", :alt => "sfwater facebook", :title => "sfwater facebook")

first_adoption_confirmation.html.erb
<a href="https://facebook.com/sfwater" style="text-decoration:none !important;">
      <%= image_tag "icons/facebook.png", :alt => "sfwater facebook", :title => "sfwater facebook" %>
    </a>

second_adoption_confirmation.html.erb
<a href="https://facebook.com/sfwater" style="text-decoration:none !important;">
      <%= image_tag "icons/facebook.png", :alt => "sfwater facebook", :title => "sfwater facebook" %>
    </a>

thank_you.html.haml
  %a{ target: '_blank', href: "https://www.facebook.com/sharer/sharer.php?u=#{root_url}" }
    %i.fa.fa-facebook-square.fa-2x

**Comment by Wilfongjt** [comment]
removed facebook/SFWater
