### ISSUE TITLE
AAD-SF uses a call-in number 415-554-3289. Replace or remove?

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#44]
## replace phone number ( 415-554-3289 ) with url ( https://www.lgrow.org/report )

~~ 415-554-3289 rings at San Francisco Public Utilities Commission.  ~~
This may be part of the public feedback discuss... a little bigger than just replacing a number.  This will require someone to answer the phone, log **the** call, ...

**Comment by Wilfongjt** [comment]
We are going to drop this issue.  I'm going to remove the phone number

**Comment by Wilfongjt** [comment]
remove number from adoptadrain-lgrow

**Comment by boekesteine** [comment]
We could keep a number on there - It would just have to go to an LGROW person's desk. Makes most sense for it to be Rachel Frantz, our Environmental Programs Associate. Her number is 616-719-4992

**Comment by Wilfongjt** [comment]
# Review Instructions
* Look for new phone number 616-719-4992 on these pages
* page url is unknown, not showing in code search

**Comment by cara-lgrow** [comment]
we do not want a phone number listed. Instead list www.lgrow.org/report

**Comment by beyondtheteal** [comment]
This phone number has been removed from the code, so it's unclear where the new email address should go. Please clarify?

**Comment by cara-lgrow** [comment]
no email address should be listed. Can you just list the webpage: www.lgrow.org/report

**Comment by beyondtheteal** [comment]
Oops, webpage. Can you clarify where it should be listed? Maybe circle a spot on a screenshot?

**Comment by cara-lgrow** [comment]
? its already linked where it needs to be in the emails, and linked in the 'what does it mean to adopt a drain' button pop-up (which is addressed in another issue).  so maybe we should close this issue, because there is not a place any longer that has a SF phone number in the app (that I can see).

**Comment by beyondtheteal** [comment]
Ok! Sounds like it is covered by other issues.

**Comment by beyondtheteal** [comment]
@Wilfongjt request to close this issue

**Comment by Wilfongjt** [comment]
no longer an issue
