### ISSUE TITLE
Heroku staging needs to be configured to run the data import

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#47]
... “docker-compose run --rm web bundle exec rake db:setup”

**Comment by jacebrowning** [comment]
Closed by https://github.com/citizenlabsgr/adopt-a-drain/pull/54

I set up a scheduled task (“Heroku Scheduler”) to pull in the latest drain data (`$ bundle exec rake data:load_things`) every night at 4am on staging.
