### ISSUE TITLE
Map Drain pop-up window

### ISSUE THREAD

**Issue by cara-lgrow** [citizenlabsgr/adopt-a-drain#5]
LGROW's requests for what the pop up window looks like when you click on a storm drain icon on the map

**Comment by cara-lgrow** [comment]
[Things to include in the pop up.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a737f09cafb1c0011849739/125516c66e82c728ace21e0d46dc9c932d8590e99be6ff4aaa5efc812d43677a2744b72375c5f327af026e114d435cec03070511afbd9b21b4b36d74df5902e5823f5720ce6f42acb8834bba05b273da4d97aaaec81d9ebc6278bec1da0d2c14171a89f55c30a1914bc151f04ee54857ac017b.docx)

**Comment by Wilfongjt** [comment]
Info Window for Not-Adopted
--------------------------------------------------------------x
| This drain is available for adoption! [Sign in] to adopt it.         |
| Discharges to <discharge-location-name>                               |
| Municipality: <municipality-name>                                            |
---------------------------------------------------------------

**Comment by Wilfongjt** [comment]
Drain Info Window for Adopted
--------------------------------------------------------------x
 drain-name || “Drain” is adopted by [adopter-user-name]! 

 Discharges to: discharge-location-name
 Municipality: municipality-name

**Comment by Wilfongjt** [comment]
# Review Instructions

## goto map and click on one of blue available drain symbols. Review the popup window 

* Look for "Give this drain a name" and a textbox to add such
* Look for "Adopt" button
* Look for "Discharges to:" and a value stating such
* Look for "Municipality" and value stating such

* Look at https://lgrow-staging.herokuapp.com

If found and is satisfactory then move issue #5 to Done on waffle.io

**Comment by cara-lgrow** [comment]
LGROW staff will review

**Comment by CourtneyCromley** [comment]
I do not see "Discharges to" or "Municipality"

**Comment by CourtneyCromley** [comment]
This has loaded to day, yesterday it wouldn't load.
