### ISSUE TITLE
Need QA Test Check-Sheet

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#53]
Quality Assurance Testers need to have a list of LGROW defined features, functions, text  to check while working their way through the application.

**Comment by jacebrowning** [comment]
We _could_ use Pull Request (PR) templates for this: https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

They can prepopulate a checklist of items on each PR for testers to go through on the review app.

**Comment by Wilfongjt** [comment]
I read the Pull Request templates page but it was mostly about the "how " of it rather than the "what.". Is there a good example out there in github land?

**Comment by jacebrowning** [comment]
Here is one: https://github.com/sdispater/poetry/blob/master/.github/PULL_REQUEST_TEMPLATE.md

They're essentially just Markdown files named `PULL_REQUEST_TEMPLATE.md` or `.github/PULL_REQUEST_TEMPLATE.md` that will prefill the body of each PR.

**Comment by Wilfongjt** [comment]
to much for small group.
