### ISSUE TITLE
Map symbols and log-in state

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#55]
Actual,
when log-in is false, the map shows only "Drains to Sewer" symbol 
when log-in is true, the current map shows "Adopted" and "Drains to Sewer" symbols

Proposed change,
when log-in is false, map shows "Adopted" and "Drains to Sewer" symbols 
when log-in is true, map shows  "Adopted", "Drains to Sewer" and "Adopted by you" symbols

**Comment by cara-lgrow** [comment]
sounds good

**Comment by Wilfongjt** [comment]
Combined with
Drain Symbolism #24
