### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#59]
When entering the site, we want to a pop-up before users enter because it offers instruction and education click-troughs. We will customize this information. This is not currently on the San Francisco site. It is on the same platform available from: St. Paul, MN https://www.adopt-a-drain.org/

![image](https://user-images.githubusercontent.com/3185699/45229838-0e06d480-b295-11e8-9f26-586b0d65cff0.png)

There are 2 different options to click through on the pop-up. We would like to keep these 2 options. We will need to change some of the language in the ‘3 Steps.’

**Comment by boekesteine** [comment]
Text for Splash Screen at https://docs.google.com/document/d/1Gji9oLWa0FCqoQ4Tq5Yz8UJeKIdk_8RfgaznEB_XqtY/edit

**Comment by Wilfongjt** [comment]
not necessary, change in redesign
