### ISSUE TITLE
AAD-SF has url to GITHUB, Remove or Replace?

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#66]
change
* https://github.com/sfbrigade/adopt-a-drain 
to
* https://github.com/citizenlabsgr/adopt-a-drain

change
* https://github.com/sfbrigade/adopt-a-drain/wiki/Windows-Development-Environment
to
* https://github.com/citizenlabsgr/adopt-a-drain/wiki/Windows-Development-Environment

**Comment by jacebrowning** [comment]
I think we should change the GitHub URL and drop the wiki link.

**Comment by Wilfongjt** [comment]
done
* https://github.com/citizenlabsgr/adopt-a-drain
* https://github.com/citizenlabsgr/adopt-a-drain/wiki/Windows-Development-Environment

**Comment by Wilfongjt** [comment]
This is really an citizen labs thing... I'll close it.
