### ISSUE TITLE
Basin Buddy - transfer accounts and adopted drains to AAD

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#73]
Another thought that I had- is there any way to import the already adopted drains from the City of Grand Rapids into this system? I'm concerned about people having to 're-adopt' their drains...but I'm not sure if there is a way around this. Something to keep in mind as development moves forward.
(transferred from Map - Fake Registrations #62 )

**Comment by Wilfongjt** [comment]
Yes, this can be done.  We need to discuss with LGROW.  We need permission from a LGROW executive and the cooperation of the database admin. We can use a google Hangout session for a quick meeting.  
Agenda:
* Request permission for LGROW to use Adopter and Adoption data from "Basin Buddy"
* Discuss Data Policy and any use restrictions
* Discuss Interoperability and , our shared understanding of Security and Privacy
* Discuss Data Policy and use restrictions
* Get written authorization to proceed

**Comment by boekesteine** [comment]
Not sure if we have discussed this since. But GR requires people to re-adopt once per year. Their suggestion was that we email everyone on their list when AAD goes live telling them that the program has been updated and their re-adoptions will need to happen via the new system. That email would come from the exiting Basin Buddy administrator. This is probably the most straightforward.

**Comment by boekesteine** [comment]
@Wilfongjt @Allen616 I discussed this issue with Mike Staal who manages GR's Basin Buddy program. They have maybe 200 people in the system right now and he has not required anyone to re-adopt for over a year (although there are a few new people in there). He affirmed what I wrote earlier and urged us not to spend time developing a complicated technical solution to migrate people over. Instead he wants to use this as an opportunity to purge the Basin Buddy list of people who are inactive. 

Next steps:
- When we are ready to perform the soft launch, Mike will email all his Basin Buddy people telling them that the program is being upgraded and they need to re-adopt on Adopt a Drain
- Citizen Labs does not need to do anything else on this issue at this time.
- LGROW will draft the email for GR - it will come from their system.
