### ISSUE TITLE
Broken Images in New Signup Email

### ISSUE THREAD

**Issue by brousch** [citizenlabsgr/adopt-a-drain#75]
The new signup email has a lot of broken images in it.

![screenshot_20180914_104015](https://user-images.githubusercontent.com/303240/45557761-529ded00-b80c-11e8-847b-74023d5d1b01.png)

![screenshot_20180914_104034](https://user-images.githubusercontent.com/303240/45557772-59c4fb00-b80c-11e8-9919-508358921df6.png)

**Comment by beyondtheteal** [comment]
Test on branch deploy works. (I'm not sure why the font looks purple in the screenshot. It looks black in real life). Work needs to be duplicated on remaining emails. 

@[boekesteine](/boekesteine) I need feedback on if the social media icons at the bottom were purposefully removed from the email format -> https://github.com/citizenlabsgr/adopt-a-drain/issues/76#issuecomment-459374891 

<img width="1042" alt="screen shot 2019-02-20 at 4 53 10 am" src="https://user-images.githubusercontent.com/39837332/53118418-0a050100-351b-11e9-8953-f62fa5844016.png">
<img width="1021" alt="screen shot 2019-02-20 at 4 53 27 am" src="https://user-images.githubusercontent.com/39837332/53118420-0a9d9780-351b-11e9-9cbd-44820326826c.png">

**Comment by beyondtheteal** [comment]
Good news, I found a way to test if the images load into the emails. This test was run on master branch code. 
<img width="1375" alt="screen shot 2019-02-24 at 12 23 32 pm" src="https://user-images.githubusercontent.com/39837332/53302717-3d070780-382f-11e9-8f8f-1908ef0e0625.png">

**Comment by Wilfongjt** [comment]
Need to update text check google

**Comment by cara-lgrow** [comment]
@beyondtheteal the text is now updated, with our original photo, at https://docs.google.com/document/d/1en7smcuMtIj7P-VY-JJT3_vkA2e7QFHzRLFAsLCnLeA/edit
it is in the 'Adopt a Drain' google drive folder doc titled: Email: First Adoption/Welcome

**Comment by beyondtheteal** [comment]
If the images are working, we should close this issue. Text update can be tracked in the other issue.

**Comment by Wilfongjt** [comment]
LGROW needs to confirm the change is as expected. I'll discuss with them.

**Comment by cara-lgrow** [comment]
Change is NOT as expected- keep item open.
The social media icons came through great- all icons are functional.

The picture of Major Runoff (water mascot) did not come through on the email, and the Adopt a Drain logo is WAY too big.
![add1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a737f09cafb1c0011849739/125516c66e82c728ace21e0d46e9909e72c0cfeb9ffbb049a15ee4d6730472727d01f6722886e170bb1a79025f5f4ff8445c5717adfb9b37b4f46d2ede0356b49b381d66cc2f10a4b2831aba03be21834e87b6ba8c4bd2a5.PNG)

**Comment by Wilfongjt** [comment]
I don't have a copy of the water masco png.  
I'm unable repeat oversized adopt-a-drain.png image.

**Comment by Wilfongjt** [comment]
I cut the water mascot out of the google doc and replaced the stub photo.  
Now we have an issue with an out of date rails install...working on it.

**Comment by Wilfongjt** [comment]
# QA
## Adopt a first drain using the map
How to check:
* https://lgrow-staging.herokuapp.com
* LOGIN with a valid email address and password
* FIND the MAP
* ABANDON any previously adopted DRAINS
* ADOPT first DRAIN
* WAIT for email to show up
* OPEN email with 'Thanks for adopting a drain' subject line
* COMPARE: EMAIL to DOCUMENT at  https://docs.google.com/document/d/18z8UMvmpe5qWEXK-u-1OwfOomDnmJT4Mai99_HpxWe8/edit?usp=sharing

**Comment by cara-lgrow** [comment]
water mascot now shows, but header logo is still too big in the emails for Outlook. Was there a solution to this, or were we just giving up? I don't remember the verdict...

**Comment by cara-lgrow** [comment]
Nevermind- Refer to issue #197
