### ISSUE TITLE
New Signup Email (Code)

### ISSUE THREAD

**Issue by brousch** [citizenlabsgr/adopt-a-drain#76]
A lot of the text content and links in the new signup email are for San Francisco.

**Comment by Wilfongjt** [comment]
This is the tip of an scaling iceberg.  The original code is built to service one city (San Francisco).  Customizing emails for a single community is easy. We now have dozens of communities and AAD doesn't have the built-in capacity to handle more than a single community.

Options:
* Rewrite the emails to get rid community specific references (Easy)
* Create a geographic context that can handle 1, 2, 3 and many communities (Medium)

**Comment by Allen616** [comment]
I haven't looked at the code. But what if the email was managed outside of the "app" and was instead passed to MailChimp? GVMC is already using MailChimp. This would provide more flexibility in creating followup email conversations (education, updates, storm warnings, regional/community, campaigns, etc lists). Mailchimp provides a lot of built in tools for management and follow up (things we then don't need to hard code) and easier to change.

**Comment by Wilfongjt** [comment]
San Fran removed. done

**Comment by boekesteine** [comment]
We have edited this email to reflect the Lower Grand River Watershed. It does not need to have every single community's info in it - just LGROW. @Wilfongjt we will email our text to you

**Comment by boekesteine** [comment]
@Wilfongjt Please see this Google Doc for updated Welcome Email text:
https://docs.google.com/document/d/18z8UMvmpe5qWEXK-u-1OwfOomDnmJT4Mai99_HpxWe8/edit?usp=sharing

**Comment by Wilfongjt** [comment]
# Review Instructions
## Prerequisites 
* Content review must be complete 

## Adopt a first drain using the map
How to check:
* https://lgrow-staging.herokuapp.com
* LOGIN with a valid email address and password
* FIND the MAP
* ABANDON any previously adopted DRAINS
* ADOPT first DRAIN
* WAIT for email to show up
* OPEN email with 'Thanks for adopting a drain' subject line
* COMPARE: EMAIL to DOCUMENT at  https://docs.google.com/document/d/18z8UMvmpe5qWEXK-u-1OwfOomDnmJT4Mai99_HpxWe8/edit?usp=sharing

**Comment by CourtneyCromley** [comment]
These  are not the same emails. The email sent from AAD to my email was a different email  than the email on that Google Doc. @Wilfongjt

**Comment by boekesteine** [comment]
The email I got was slightly different, but only in that it had an extra sentence about VIP events at the end that I think can stay. Everything else was the same. Images still broken.

**Comment by CourtneyCromley** [comment]
Here are the proper website images to hyperlink our Facebook, Twitter and Instagram to.
![flogo_RGB_HEX-72.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ba92d981d19420013999801/125516c66e82c728ace21e0d46ee9895248dbc9ba8cb806b8165bdc37b046b313916ac217586f76ae5002e005b0a4ba5490b0d4ca8f1db78a6b63d248f5803be806f4d68d47f40f2ecdd42e64bef62994597b7bb804dc5ed3d22e0898c4b381a021c9bb2.png)
![Instagram Logo.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ba92d981d19420013999801/125516c66e82c728ace21e0d46c19a89378384bb8ee4ff6fab5affd665043761260ea62864c7b96aea432f045a5646ff13500b4caeaa892ba7e23974820f5aefc3714d36976345f3e5db55ea43a82a994d84bcbd8f49c0ef3a27e48e8a463f1d1755.png)
![Twitter_Logo_Blue.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ba92d981d19420013999801/125516c66e82c728ace21e0d46dc8393379686bbb0c5b044ab62d2983c43653f6b14b1247a80e03cfd1839540e5b1ba948500c16f4ad8179f5b63c71de590fe5823c5d66da2f53fde6d640e258f075c95d8fa4bd8246c1ed3825e08c8d4c3b17021d8fed10.png)

**Comment by cara-lgrow** [comment]
I'm not sure what is going on with google docs, but this is the welcome email that should be going out- it has updated social media icons with hyperlinks:
[Adopt a Drain Welcome Email.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a737f09cafb1c0011849739/125516c66e82c728ace21e0d46c990953396c3a8cfcdad42ad53b0a32c4a247c2401e30e7d84ea24fd0e39111d0014f9121c4d4eeefcd82ff3b33578d90e03b9d93f0c74c63c45a9bc8a4cee03a83c990dd4e8e8d51199a26867f5819d4e3914041d8cff5a3da0904fc951f34bf300.docx)

**Comment by cara-lgrow** [comment]
I'm not sure what is going on with google docs, but this is the welcome email that should be going out- it has updated social media icons with hyperlinks:
[Adopt a Drain Welcome Email.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a737f09cafb1c0011849739/125516c66e82c728ace21e0d46c990953396c3a8cfcdad42ad53b0a32c4a247c2401e30e7d84ea24fd0e39111d0014f9121c4d4eeefcd82ff3b33578d90e03b9d93f0c74c63c45a9bc8a4cee03a83c990dd4e8e8d51199a26867f5819d4e3914041d8cff5531a9914ccd58f04af300.docx)
