### ISSUE TITLE
Question Survey (Google form)

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#85]
Objective:
* Get feedback on AAD 
* replaces existing function

Strategy:
* Use a google form to collect simple feed back about AAD
* Model form on the SF feedback page http://goo.gl/forms/sD3lniSd4b
* post url to form here for developer https://goo.gl/forms/KWU663uQiAXT5Y6o1

**Comment by boekesteine** [comment]
Do you want feedback on what questions to include on this survey? Here's my thought:
1. How did you hear about AAD? (Facebook, Email, Instagram, Website, Someone told me in person, At an event)
2. Why did you decide to adopt a drain? (Check all that apply - I like doing my part to protect the Lower Grand River Watershed, I want to keep my neighborhood looking clean, I want to reduce flooding on my street, Someone (like a teacher) told me I should,  Other)
3. How likely are you to recommend Adopt a Drain to a friend, neighbor, or colleague?

**Comment by Wilfongjt** [comment]
# Seems like we have at least two themes
* Feedback about the app: Report an Issue or a way to improve adopt-a-drain
* Feedback about the user:  Marketing Survey

**Comment by cara-lgrow** [comment]
Feedback about the user would be more valuable to us as an organization, in hopes that feedback about the app would be given to us via the contact email listed in the app.
