### ISSUE TITLE
Configure Production Domain Name (by March 29)

### ISSUE THREAD

**Issue by Wilfongjt** [citizenlabsgr/adopt-a-drain#87]
# Objective:
Deploy AAD into production

# Strategy
* Domain Name installation should be among the last things done before going live
* adoptadrain-lgrow.org is the domain name
* LGROW has purchased the DN
* [Custom Domain Names for Apps](https://devcenter.heroku.com/articles/custom-domains)
* Complete task by March 29

# Related Issues
* #166 April 1 Soft launch
# Note
* Once installed the DN may take a day to be fully functional

**Comment by cara-lgrow** [comment]
LGROW owns the domain: adoptadrain-lgrow.org

**Comment by cara-lgrow** [comment]
@Wilfongjt let us know what needs to happen on our end. Also, this date should be March 27, correct?

**Comment by Wilfongjt** [comment]
@cara-lgrow the domain name rollover is scheduled for the 29th. 
This should be on your calendar.

**Comment by cara-lgrow** [comment]
@Wilfongjt yes! the title of this issue is April 27 though- just wanted to make sure we were in the same month. You have to keep us on task!

**Comment by jacebrowning** [comment]
https://www.adoptadrain-lgrow.org/
