### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by Allen616** [citizenlabsgr/adopt-a-drain#9]
Identify, document, and test multiple adoption process models

**Comment by rebeccaallard** [comment]
Identify, document, and test multiple adoption process models

**Comment by rebeccaallard** [comment]
Accidentally closed this card

**Comment by Wilfongjt** [comment]
We need some clarification on this issue.  How about establishing a set of Objectives to guide the development of new adoption processes.  

For example, given the following sample objectives 
## Sample Objectives:
* quickly adopt one or more drains
* adopt one or more drains by a visually impaired user 

The processes for these objectives are going to be very different.
