### ISSUE TITLE
Address search broken

### ISSUE THREAD

**Issue by cara-lgrow** [citizenlabsgr/adopt-a-drain#97]
## Problem
* Address search worked in the past... something has change to break it 
## Issues
* Google Geocoder requires an API Key,  none found

**Comment by beyondtheteal** [comment]
SF is having the same problem! We should consider sharing our fix once it's done 

https://github.com/sfbrigade/adopt-a-drain/issues/360

**Comment by BrandonKlotz** [comment]
That is a great idea!

**Comment by cara-lgrow** [comment]
Works great. Can search via address or business.
