### ISSUE TITLE
Change 'X drains adopted in GRB' to 'X drains adopted in LGRW'

### ISSUE THREAD

**Issue by cara-lgrow** [citizenlabsgr/adopt-a-drain#98]

**Comment by Wilfongjt** [comment]
# Review Instructions

Task: Substitute "LGROW" for "GRB" 

* goto home page, look for "N Drains adopted in LGROW".

* https://lgrow-staging.herokuapp.com

if found and satisfactory then move issue #98 to Done in waffle.io
